version: "3.9"

services:
  ##############################################################################
  # Nginx
  ##############################################################################
  nginx:
    build: ./docker/nginx
    ports:
      - 5080:80
    networks:
      - backend

  ##############################################################################
  # Server 1
  ##############################################################################
  app-server-1:
    build: ./docker/node
    hostname: app-1
    networks:
      - backend

  ##############################################################################
  # Server 2
  ##############################################################################
  app-server-2:
    build: ./docker/node
    hostname: app-2
    networks:
      - backend

  ##############################################################################
  # Server 3
  ##############################################################################
  app-server-3:
    build: ./docker/node
    hostname: app-3
    networks:
      - backend

################################################################################
# Networks
################################################################################
networks:
  backend: null
