version: "3.9"

services:
  ##############################################################################
  # Nginx
  ##############################################################################
  nginx:
    build: ./docker/nginx
    ports:
      - 5080:80
    networks:
      - backend
    depends_on:
      - app-server-1
      - app-server-2
      - app-server-3

  ##############################################################################
  # App Servers
  ##############################################################################
  app-server-1:
    build: ./docker/python
    hostname: app-server-1
    networks:
      - backend
      - db-backend
    depends_on:
      - redis

  app-server-2:
    build: ./docker/python
    hostname: app-server-2
    networks:
      - backend
      - db-backend
    depends_on:
      - redis

  app-server-3:
    build: ./docker/python
    hostname: app-server-3
    networks:
      - backend
      - db-backend
    depends_on:
      - redis

  ##############################################################################
  # Redis
  ##############################################################################
  redis:
    build: ./docker/redis
    networks:
      - db-backend

################################################################################
# Networks
################################################################################
networks:
  backend: null
  db-backend: null
