version: "3.9"

services:
  ##############################################################################
  # Nginx
  ##############################################################################
  nginx:
    build: ./docker/nginx
    ports:
      - 5080:80
    networks:
      - backend
    depends_on:
      - varnish

  ##############################################################################
  # Cache
  ##############################################################################
  varnish:
    build: ./docker/varnish
    networks:
      - backend
    depends_on:
      - app-server

  ##############################################################################
  # Server
  ##############################################################################
  app-server:
    build: ./docker/node
    hostname: app-server
    networks:
      - backend

################################################################################
# Networks
################################################################################
networks:
  backend: null
