version: "3.9"

services:
  ##############################################################################
  # Nginx
  ##############################################################################
  nginx:
    build: ./docker/nginx
    ports:
      - "5080:80"
