################################################################################
# HAProxy
################################################################################
FROM haproxy:2.4-alpine as haproxy
 
COPY haproxy.cfg /usr/local/etc/haproxy/haproxy.cfg
