services:

  ##############################################################################
  # HAProxy
  ##############################################################################
  haproxy:
    build: ./docker/haproxy
    hostname: haproxy
    networks:
      - backend
    ports:
      - "127.0.0.1:5080:80"
      - "127.0.0.1:5081:81"
    depends_on:
      - node-server-1
      - node-server-2
      - node-server-3
      - node-server-4
      - node-server-5

  ##############################################################################
  # Server 1
  ##############################################################################
  node-server-1:
    build: ./docker/node
    hostname: node-server-1
    networks:
      - backend

  ##############################################################################
  # Server 2
  ##############################################################################
  node-server-2:
    build: ./docker/node
    hostname: node-server-2
    networks:
      - backend

  ##############################################################################
  # Server 3
  ##############################################################################
  node-server-3:
    build: ./docker/node
    hostname: node-server-3
    networks:
      - backend

  ##############################################################################
  # Server 4
  ##############################################################################
  node-server-4:
    build: ./docker/node
    hostname: node-server-4
    networks:
      - backend

  ##############################################################################
  # Server 5
  ##############################################################################
  node-server-5:
    build: ./docker/node
    hostname: node-server-5
    networks:
      - backend

################################################################################
# Networks
################################################################################
networks:
  backend: null
