services:
  ##############################################################################
  # Nginx
  ##############################################################################
  nginx:
    build: ./docker/nginx
    ports:
      - 127.0.0.1:5080:80
    networks:
      - backend
    depends_on:
      - php-fpm

  ##############################################################################
  # PHP-fpm
  ##############################################################################
  php-fpm:
    build: ./docker/php-fpm
    networks:
      - backend

################################################################################
# Networks
################################################################################
networks:
  backend: null
